### ISSUE TITLE
Sửa mô tả đồ án phần giới thiệu

### ISSUE THREAD

**Issue by nguyendacthienngan** [nguyendacthienngan/QuanLyNhaHang#2]
Điều chỉnh phần giới thiệu phù hợp với yêu cầu của thầy.

**Comment by tran-bao** [comment]
Đối với các mô hình nhà hàng vừa và lớn, việc lựa chọn phương pháp quản lý chưa bao giờ là dễ dàng. Với mong muốn mang đến sự tin tưởng và tiện ích, chúng tôi xin giới thiệu ứng dụng quản lí nhà hàng ABCXYZ. 
 Sở hữu giao diện thân thiện, phân quyền rõ ràng cùng với những tính năng nổi bật trong nghiệp vụ bán hàng lẫn quản lý bao gồm: bàn ăn, nhân viên, khách hàng, thanh toán,...
(Ngoài ra còn cung cấp các tính năng theo dõi doanh thu, đưa ra gợi ý, chương trình khuyến mãi, trò chơi,...)
 ABC tự tin trở thành trợ thủ đắc lực trong quá trình phát triển bền vững !!
