### ISSUE TITLE
Hoàn thiện Roadmap và Plan

### ISSUE THREAD

**Issue by nguyendacthienngan** [nguyendacthienngan/QuanLyNhaHang#3]
Tiên sẽ cập nhật thêm giao diện trong phần Roadmap và chỉnh sửa Plan (Kế hoạch chi tiết) trong file README.md

**Comment by Bao-Tien** [comment]
OK Ngân

**Comment by Bao-Tien** [comment]
T tạo nhánh Roadmap-edits để t chỉnh sửa trên đó rồi có gì bà check nha Ngân.

**Comment by nguyendacthienngan** [comment]
Ok nha
