### ISSUE TITLE
Soạn cuốn Báo cáo (6/10) (14/12/2019) (18/12/2019)

### ISSUE THREAD

**Issue by nguyendacthienngan** [nguyendacthienngan/QuanLyNhaHang#35]
Bảo sẽ hỗ trợ dàn trang, đánh số trang và đi in cuốn Báo Cáo nhé

**Comment by tran-bao** [comment]
[UIT_Phu-luc-3_Mau-bao-cao.docx](https://github.com/nguyendacthienngan/QuanLyNhaHang/files/3955762/UIT_Phu-luc-3_Mau-bao-cao.docx)
Tui hiện đã làm được 1/3 cuốn rồi nha

**Comment by tran-bao** [comment]
[UIT_Phu-luc-3_Mau-bao-cao.docx](https://github.com/nguyendacthienngan/QuanLyNhaHang/files/3961171/UIT_Phu-luc-3_Mau-bao-cao.docx)
Cập nhật lại datagram mới

**Comment by nguyendacthienngan** [comment]
Bảo hỏi chỗ in sau trường mình giá tiền như thế nào, in sao nha. Sẵn hỏi về vụ làm đĩa CD sao luôn nha
